name: Node.js CI

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm i -g @microsoft/rush yarn
      - run: rush install
      - run: rush build
      - run: rushx test
